name: Build and deploy backend to Azure Web App - capellaops-api-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate backend
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m compileall app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D3C804640C524777867062ED4D0B9348 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_009E4C2DB69E46C194C468D5B4115D97 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FFA962AEBCF4FA7A0735B3E8288FF09 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'capellaops-api-prod'
          slot-name: 'Production'
          package: 'backend'     
